version: '2.1'
services:

  app:
    build: 'app'
    restart: on-failure
    ports:
      - 8888:80

  db:
    build: 'db'
    restart: on-failure
    ports:
      - 5444:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20

  server:
    build: 'server'
    restart: on-failure
    environment:
      - DB_HOST=localhost
      - DB_PORT=5444
      - DB_NAME=tododb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - API_HOST=localhost
      - API_PORT=8889
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy

